#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 02 21:35:00 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=VanillaPlus_v3.3.zip
enableShaders=false
